### ISSUE TITLE
图片上传问题

### ISSUE THREAD

**Issue by unosky** [wuzhicms/wuzhicms#3]
* PHP5.2下   /index.php?m=core&f=index&_su=wuzhicms打开后台会跳转到首页去
* PHP5.4下无法上传图片
* PHP5.5.18下 编辑器可以传图 组图可以上传 附件管理中模块配置 附件上传测试 点上传按钮 提示参数错误!
![image](https://cloud.githubusercontent.com/assets/4272180/7706939/e089feaa-fe7f-11e4-8c69-17143339ebdb.png)

**Comment by wuzhicms** [comment]
已修复！
