### ISSUE TITLE
后台管理员存在的两套密码机制

### ISSUE THREAD

**Issue by lifesign** [wuzhicms/wuzhicms#35]
目前会员其实统一在一张 member 表中，但是又存在一张 admin 的表，而且根据现有的机制，如果是后台登陆可以设置独立密码，否则和前台用户相同。 如果后台用户修改了密码，会导致存在两个密码可以进入后台，风险更大。 因此，密码是不是统一用一套就可以了，毕竟有权限可以限制。

**Comment by wuzhicms** [comment]
如果修改了后台密码，前台密码如果也能登陆那就是bug。这个我们验证下。

**Comment by wuzhicms** [comment]
已修复。感谢反馈
