### ISSUE TITLE
5.31号下载的无法把configs coreframe 放到www目录

### ISSUE THREAD

**Issue by q889518** [wuzhicms/wuzhicms#56]
5.31号下载的无法把configs coreframe 放到www目录
放到www目录后无法安装

第1步，开始配置数据库文件： www/mysql_config.php
数据库配置文件： www/mysql_config.php 成功 
第2步，开始配置网站信息文件：www/web_config.php
网站信息配置文件：www/web_config.php 写入成功 
第3步，开始配置文件：coreframe/configs/wz_config.php

就不动了 放到www目录外就没事

**Comment by wuzhicms** [comment]
收到，待验证！

**Comment by wuzhicms** [comment]
已修复！
