### ISSUE TITLE
五指CMS 再见 

### ISSUE THREAD

**Issue by q889518** [wuzhicms/wuzhicms#65]
一直在群里潜水 这几天有好几位群友反应放到一起无法执行
一位群友遭到了大家的围攻 原因是管理说了不建议放在一起
试问下管理这样说真的好吗？这真的不属于BUG？
上次说验证码不显示的也时候也是被群殴 官方悄悄修复了
这次又是被群殴 太他妈的生气了 找bug没奖励也就算了 还受气 
 以后也不再反馈bug了 免得遭到围攻 
五指CMS 再见

**Comment by q889518** [comment]
没有注册论坛账户 只能借助这个地方发泄下心里愤怒的心情了 我也理解的管理的话是什么意思
尽量的分开 这样安全，我只是就事论事的说有时候需要放在一起 有的公司服务器是严格限制的 好家伙你看看群里的水军 就开始喷了 再见了 走了一个我不算什么 即便走我也要把原因讲清楚了
反馈问题都能这样 天理何在？

**Comment by wuzhicms** [comment]
非常抱歉看到这个消息，放到一起无法执行，这个肯定是bug，我们测试后，会修复。
同时，这个互联网就是因为不实名，所以会有一些人喜欢攻击别人。
不要因为一些无聊的人，无知的人生气。希望继续支持我们！
