### ISSUE TITLE
角色无栏目管理权限时报错

### ISSUE THREAD

**Issue by hetoo** [wuzhicms/wuzhicms#75]
不赋予角色任何内容管理权限时，报错。

![1](https://cloud.githubusercontent.com/assets/7521166/16541745/77ca5586-40be-11e6-9435-816dcf5e1967.png)
![2](https://cloud.githubusercontent.com/assets/7521166/16541746/7c2d9278-40be-11e6-8dfa-6b59b41b0b06.png)

**Comment by wuzhicms** [comment]
已修复： https://github.com/wuzhicms/wuzhicms/commit/c5e6af456a6cb104b71b57e2eb191c94335e1ac9
