### ISSUE TITLE
角色不赋予删除会员权限的问题

### ISSUE THREAD

**Issue by hetoo** [wuzhicms/wuzhicms#76]
角色不赋予删除会员权限时，依然显示删除按钮
![1](https://cloud.githubusercontent.com/assets/7521166/16541767/3bfdac32-40bf-11e6-8153-23bd18702ecc.png)

![2](https://cloud.githubusercontent.com/assets/7521166/16541760/f5aad66a-40be-11e6-86f2-0532c0ba9ba3.png)

**Comment by wuzhicms** [comment]
点击之后会有无权限显示。
目前只能做到顶部菜单和左侧菜单根据权限显示。
正文里面的编辑，修改。排序等。没有必要每个都加权限是否显示判断。这样开发成本太大了。
