### ISSUE TITLE
Tag添加和修改无效

### ISSUE THREAD

**Issue by hetoo** [wuzhicms/wuzhicms#79]
处理办法：
coreframe\app\tags\admin\template\add.tpl.php
第86行修改为
`<input class="btn btn-info col-sm-12 col-xs-12" type="submit" name="dosubmit" value="<?php echo L('submit');?>">`

**Comment by wuzhicms** [comment]
已修复：https://github.com/wuzhicms/wuzhicms/commit/09eaeb77d22d22e307deea478660123d44fd8f81
