### ISSUE TITLE
联动菜单添加选项提示字段缺少！

### ISSUE THREAD

**Issue by pifupai** [wuzhicms/wuzhicms#84]
联动菜单在添加选项的时候提示缺少字段的问题；

[sql_error]MySQL Query Error

INSERT INTO `wz_linkage_data`(`remark`,`linkageid`,`pid`,`name`,`initial`,`thumb`,`pictures`) VALUES ('','6','0','我的','WODE','','')
[msg]Unknown column 'initial' in 'field list';

五指版本3.0.4

**Comment by wuzhicms** [comment]
已修复
