### ISSUE TITLE
关于更新缓存的BUG；

### ISSUE THREAD

**Issue by pifupai** [wuzhicms/wuzhicms#92]
比如说联动菜单，新增加或者删除后；去后台选择更新缓存，但实际更新缓存无效，要手动在缓存目录删除对应的缓存文件后，才显示正常。
这个BUG也很严重~

**Comment by wuzhicms** [comment]
这个应该是你 windows的权限配置问题。把文件和文件夹设置 iiis访客用户，或者everyone可读写
