### ISSUE TITLE
关于后台删除记录的BUG~~~

### ISSUE THREAD

**Issue by pifupai** [wuzhicms/wuzhicms#93]
删除功能的BUG！！！
后台系统不管是删除文章，还是删除联动菜单，还是别的；删除后，后台界面是看不到了，但数据库里依然存在；
这导致前台还依然显示数据；也就是说删除功能其实只是删除了当前HTML元素，并没有实际删除任何SQL记录，这个问题很严重的BUG！

**Comment by wuzhicms** [comment]
删除的文章在回收站。可以在回收站清空。
