### ISSUE TITLE
真是奇葩，论坛注册后反而看帖子权限都没有了！

### ISSUE THREAD

**Issue by drny** [wuzhicms/wuzhicms#96]
本来想在论坛里提问的，注册了反而看帖子权限都没有了，发帖也要等30分钟，是不是30分钟过了发帖又提示你的账号还没通过人工审核！

安装都安装不上：

第1步，开始配置数据库文件： www/mysql_config.php
安装遇到问题：

Warning: unlink(E:/www/configs/mysql_config.php): Permission denied in E:\www\install\index.php on line 383

Warning: rename(E:/www/configs/default_mysql_config.php,E:/www/configs/mysql_config.php): in E:\www\install\index.php on line 385

Warning: rename(E:/www/configs/default_uc_mysql_config.php,E:/www/configs/uc_mysql_config.php): in E:\www\install\index.php on line 389

Warning: rename(E:/www/configs/default_weixin_config.php,E:/www/configs/weixin_config.php): in E:\www\install\index.php on line 393

Warning: rename(E:/www/configs/default_route_config.php,E:/www/configs/route_config.php): in E:\www\install\index.php on line 397
1

**Comment by wuzhicms** [comment]
下载发布包
